version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres

  nest-redis:
    container_name: nest-redis
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    env_file:
      - .env
    volumes:
      - nest-redis:/var/lib/redis/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 1s
      timeout: 3s
      retries: 30

volumes:
  postgres:
    name: nest-postgres-db
  nest-redis:
    name: nest-redis-db